trigger:
  branches:
    include:
      - main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'springbootapp'

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: Docker@2
      inputs:
        containerRegistry: 'dev-identity'
        repository: 'springbootapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
